// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;


namespace HW1
{
public class BasePage {
  public static IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  public IJavaScriptExecutor js;

  public void Initialize() {
    driver = new ChromeDriver(@"C:\Users\BeyzaOZTURK\Documents\GitHub\BeyzaNurOzturk_Homework\Week4\HW1");
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
    driver.Navigate().GoToUrl("https://www.dr.com.tr/");
    driver.Manage().Window.Size = new System.Drawing.Size(1892, 1015);
  }
 
  public void TearDown() {
    driver.Quit();
  }
}
}