// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.PageObjects;


namespace HW1
{
public class HomePage   :   BasePage{

  public void HomePage (IWebDriver driver) {
    HomePage.driver = driver;
    PageFactory.InitElements(driver,this);
  }
  
  [FindsBy(How=How.CssSelector, Using =".search-input")]
   private IWebElement search;

  [FindsBy(How=How.CssSelector,Using =".product-img > a")]
   private IWebElement product;
   
  [FindsBy(How=How.CssSelector,Using =".col-sm-8")]
   private IWebElement basket;

    public void SearchProduct() {
    search.Click();
    search.SendKeys("ben kirke");
    search.SendKeys(Keys.Enter);
  }
    public void AddBasketProduct() {
    SearchProduct();
    product.Click();
    basket.Click();
  }
  
}
}